### ISSUE TITLE
Text leaks in widgets and notes

### ISSUE THREAD

**Issue by MinecraftPublisher** [anyproto/anytype-swift#1403]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

1. I create note "A" as follows:
```
# "A"
Hello world!
```
2. I add a note "A" as a widget.
3. I add note links inside note "A" to note "B".
4. I set the contents of note "B" as follows:
```
# Title
Sub description that I don't want to appear in the widget
```
5. I go back to the main screen to see my note "A" widget:
6. It looks like this:
![IMG_9218](https://github.com/anyproto/anytype-swift/assets/44898501/fad9b8a5-bd67-490d-852a-1a9149456c0a)

### Expected Behavior

When a title is set for a note, It should not also show descriptions from the note itself in a widget. This expectation also applies to note links inside of notes.

### Steps To Reproduce

Provided above.

### Environment

```markdown
- OS: iOS 17.4.1
- Version: 0.29.3 build 1 library v0.33.2
```

### Anything else?

![IMG_9218](https://github.com/anyproto/anytype-swift/assets/44898501/eb473b66-dff1-413e-91e0-39a649fef12d)

**Comment by MinecraftPublisher** [comment]
Or alternatively, Add an option to toggle this feature.

**Comment by ignatovv** [comment]
We have plans to update notes behaviour. 
We use [community forum](https://community.anytype.io/) as a single source of truth for product feature requests. We are using Github only for engineering related issues, where no product team members should be involved. There should be a big discussion regarding notes already
