### ISSUE TITLE
Easier exports

### ISSUE THREAD

**Issue by MinecraftPublisher** [anyproto/anytype-swift#1404]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

Currently, Exporting on mobile involves meticulously selecting _every block_ in the note and then clicking copy to export it as markdown.

### Suggested solution

Add a "Select all" button to notes. or alternatively, A "Copy all" button.

**Comment by ignatovv** [comment]
Implemented in upcoming release. Eta: 1-2 weeks
