### ISSUE TITLE
enhancement of receiving sharing

### ISSUE THREAD

**Issue by hellodword** [anyproto/anytype-swift#1734]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

Thank you for providing such an amazing app, Anytype!

I have recently been using Anytype on iOS and would like to describe some minor issues I encountered when sharing from other apps. Please correct me if I have missed anything:

1. For the same random [URL](https://news.ycombinator.com/item?id=36799548), when I share it from Safari to Anytype, it correctly prompts to SAVE AS `Bookmark Object` or `Link Block`. However, when I share it from [Firefox Focus](https://www.mozilla.org/en-US/firefox/browsers/mobile/focus/) to Anytype, it only prompts to SAVE AS `Note object` or `Blocks`.

2. A similar issue occurs if I select the pure text `https://news.ycombinator.com/item?id=36799548` from anywhere and then use the [built-in](https://support.apple.com/en-gb/guide/iphone/iph1a9cae52c/ios) system `Share...` option to share it to Anytype. It also only prompts to SAVE AS `Note object` or `Blocks`.

### Suggested solution

Therefore, I have the following suggestions:

1. Enhance URL recognition when receiving shares, for instance, by matching the shared plain text that happens to be a URL and prioritizing it as a `Bookmark Object` or `Link Block`.

2. Provide more options in the SAVE AS menu when receiving shares, such as allowing the free selection of `Bookmark Object` or `Note object`, the option to add to specific Sets, or setting Tags for a `Bookmark Object` directly without needing to find and click several times within the app.

**Comment by ignatovv** [comment]
Thank you for your inquiry, @hellodword. However, Firefox Focus is not in the list of software we support, and we do not have the capacity for this one. Consider making a contribution yourself.
