### ISSUE TITLE
Add LateX support

### ISSUE THREAD

**Issue by Notme112** [anyproto/anytype-swift#1897]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

Hey everyone,
LaTeX-blocks created on another machine are shown as unsupported block on iPadOS. Inline Latex is shown as $f(x) = x^2$ and not rendered
<img width="370" alt="image" src="https://github.com/user-attachments/assets/fe640f59-e0fb-4be6-94da-454475486dfd">
I would be very glad if someone can have a look at this. According to the App Store I‘m using the newest version of Anytype.

### Suggested solution

Add support for LaTeX, inline blocks or full block doesn’t matter, one would be enough at the moment

### Alternative

Show LateX-Blocks as text and not as unsupported

### Additional context

Have a nice day!
Greets

**Comment by ignatovv** [comment]
Hello, Notme112. We use [community forum](https://community.anytype.io/) as a single source of truth for product feature requests. We are using Github only for engineering related issues, where no product team members should be involved. Feel free to create feature request there if it's still an actual thing. There should be already a thread about this issue.
