### ISSUE TITLE
Cannot create new type in ios client

### ISSUE THREAD

**Issue by schmurian** [anyproto/anytype-swift#203]
In the [documentation](https://doc.anytype.io/d/anytype-basics/types/create-a-new-type) it says I can create a new type by navigating to the Search menu.

When typing a new type into the search bar, I can see the message "There is no type named Animal
Create a new one or search for something else".

However, no button appears to add a new type, which prevents me from creating a new type.

![image](https://github.com/anyproto/anytype-swift/assets/46840747/570be3c7-0653-48a5-8e0a-f5f6776bbffd)

**Comment by bududomasidet** [comment]
Hi @schmurian.
You are right, it is still not possible to create a object type in iOS. 
On Desktop or Android you can find a Library tab where all your types are located. For now you can create a new types only on Desktop and Android
Seems like we need to change typo in this screen. @kmordan 

Thank you for your report, app library on iOS would be implemented soon.
