### ISSUE TITLE
Cannot connect on iPad to my new account via Backup Phrase

### ISSUE THREAD

**Issue by schmurian** [anyproto/anytype-swift#204]
When trying to connect my new account from my iPhone to my iPad, the iPad displays a Account Error message.

Also, the Profile page on my iPhone doesn't show a QR code.

When trying to connect the other way round (iPad to iPhone) it shows a message that I need to migrate my account by downloading the desktop app.

Do I need a desktop app to sync between 2 iOS devices?

**Comment by bududomasidet** [comment]
Thanks for reporting @schmurian 

May I ask you to give an additional information please. Could you share your account info from screen I provided in attachement. You should be able to copy it by simply tapping on Tech info section
![IMG_FC69208FD6F3-1](https://github.com/anyproto/anytype-swift/assets/15055998/cf6951f3-c4ce-4e0c-8c97-6c24957f2503)

**Comment by schmurian** [comment]
Hi,
Sure

’’’
Device: iPhone 12 mini
OS version: 16.5.1
App version: 0.23.4
Build number: 1
Library version: v0.27.15
Account ID: A9EFBSkujTGidVe72Cyct6CQJ75aHd7s6u7JMCwkzFTrBsc7
Device ID: A8YgD6pbq14ByJi6kL6CCcjPYJFNQ5NtpEUrXwpiYcaJj23w
Analytics ID: 2b114314-ec8c-46d6-a574-fd6ae9771c05
’’’

**Comment by schmurian** [comment]
Does this give away any personal identifiable information?

**Comment by bududomasidet** [comment]
Thank you for providing addtional information. We'll try to investigate what happens here.

> Does this give away any personal identifiable information?

No it gives just an account id. 
It would never disclose your data storing in your accout. But, to avoid any additional problems I should delete it.

**Comment by schmurian** [comment]
Ok, looks like I need to connect my Desktop machine first.
Then I can use the QR code to connect another iOS device.
Hm, I hoped it would work without a desktop app...

**Comment by mgolovko** [comment]
@schmurian, Hello. You can use the seed phrase for login on another iOS device. We added feature request to implement qr code on mobile.
What about sync. For now, P2P doesn't work very well on iOS. For login on other device, you should enable network sync.

**Comment by ignatovv** [comment]
We dramatically increased quality of p2p sync in recent releases, I hope it will help.
Regarding feature request about qr code - we have it in mind, but you are welcome to open a reature request on [community forum](https://community.anytype.io/). We use forum as a single source of truth for product feature requests.
