### ISSUE TITLE
Sync only works with at least one Desktop node if cloud connection is blocked

### ISSUE THREAD

**Issue by schmurian** [anyproto/anytype-swift#207]
I tried to find out how data is synced locally, if I block the connection to the cloud storage.
If the desktop app is not open, peer-to-peer is not working between 2 iOS devices

**Comment by mgolovko** [comment]
@schmurian hello. P2P on iOS now doesn't work very well. We are working for fixing this problem.

**Comment by emondhar** [comment]
Any updates?

**Comment by ignatovv** [comment]
We dramatically increased the quality of p2p sync in the upcoming release; I hope it will help. Eta: 1-2 weeks.
