### ISSUE TITLE
System mode not syncing with device theme

### ISSUE THREAD

**Issue by leo29plns** [anyproto/anytype-swift#2156]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [x] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

Both light and dark modes are working, but since iOS 18.0, Anytype stays in dark mode, even if the device is set to light mode.

### Expected Behavior

Anytype should follow the device’s theme while in “system mode.” When the device switches between light and dark modes, the application should automatically adjust accordingly.

### Steps To Reproduce

1. Set the device’s theme to “light mode.”
2. Open the application and set the theme to “system mode.”
3. Observe that the application remains in dark mode despite the device being in light mode.

### Environment

```markdown
- OS: iOS 18
- Version:0.32.3
```

### Anything else?

Thanks :)

**Comment by ignatovv** [comment]
Already fixed and will be shipped in upcoming release 🙏
