### ISSUE TITLE
“Split View” and “Slide Over” OS features support in iPad app

### ISSUE THREAD

**Issue by e1sordo** [anyproto/anytype-swift#2179]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

Hey, guys! Any insights or plans to add support for these two features to the app?

### Suggested solution

_It is clear from the name of this request_

**Comment by ignatovv** [comment]
Hello e1sordo. We use [community forum](https://community.anytype.io/) as a single source of truth for product feature requests. We are using Github only for engineering related issues, where no product team members should be involved. Feel free to create feature request there if it's still an actual thing. There should be already thread about iPad support.
