### ISSUE TITLE
Use Face ID to unlock the app before showing its contents

### ISSUE THREAD

**Issue by genericbar** [anyproto/anytype-swift#557]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

At the moment there's no way of securing access to the app's content on iOS. Once the phone is unlocked anyone can access its contents which isn't great.

### Suggested solution

Add the ability to verify the current user with Face ID upon launching before it unlocks and displays the app's content.

**Comment by kannishk** [comment]
Can I be assigned this?

**Comment by kmordan** [comment]
@genericbar Hey! We will consider it next year as part of https://github.com/anyproto/roadmap/issues/41

**Comment by kannishk** [comment]
Would love to work on it if its not a problem

**Comment by LindenLiu** [comment]
Would love to see the feature. Let me know if you need anyone work on this feature!

**Comment by duracell** [comment]
Face-ID requirement can be set on iOS 18 for every 3rd party app.
Just hold the icon on the home screen.
Maybe this helps :)

**Comment by ignatovv** [comment]
Hello everyone. We use [community forum](https://community.anytype.io/) as a single source of truth for product feature requests. We are using Github only for engineering related issues, where no product team members should be involved. Feel free to create feature request there if it's still an actual thing.
