### ISSUE TITLE
Deleted multiple lines of text doesn't work, cursor gets stuck at rginning of line

### ISSUE THREAD

**Issue by mb0x88** [anyproto/anytype-swift#814]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

When i delete a line of text, the cursor gets stuck on the current line , at the beginning of the line and doesn't continue deleteing the line above

### Expected Behavior

If i hold down the delete key, I expect it to keep deleteing text, jumping to line above until i release my finger.

### Steps To Reproduce

1. on a page with multiple lines of text
2. hold down the delete key on the bottom line of text
3. cursor gets stuck at the beginning of the line

### Environment

```markdown
- OS: iOS 15.8
- Version: 0.27.1
```

### Anything else?

https://github.com/anyproto/anytype-swift/assets/106029773/779b1058-aefa-4f10-8407-ce3eae3a4808

**Comment by MinecraftPublisher** [comment]
This is because each line is considered a different block. Try long pressing on one line, And when it turns yellow, Tap to select the others, Then press delete on the menu that appears at the bottom.

**Comment by ignatovv** [comment]
This is considered an expected behaviour as MinecraftPublisher mentioned above
